import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import ContentWrapper from '../components/ContentWrapper';
import Blog from '../components/Blog';
import Footer from '../components/Footer';

const URL = process.env.STRAPIBASEURL

export async function getStaticProps() {
  const fetchParams = {
    method: "post",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify({
      query: `{
      blogposts {
        title
        blogbody
        description
        slug
        splash {
          url
        }
      }}
      `
    })
  }

  const res = await fetch(`${URL}/graphql`, fetchParams);
  const { data } = await res.json();

  return {
    props: data,
    revalidate: 10,
  }
}

export default function Home({ blogposts }) {
  return (
    <ContentWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Dev.IO!</a>
        </h1>

        <div className={styles.grid}>
          {blogposts.map((blog, index) => {
            const { title, description, slug } = blog;
            return <Blog key={index} title={title} description={description} slug={slug} />
          })}
        </div>
      </main>
      <Footer />
    </ContentWrapper>
  )
}
